### ISSUE TITLE
npm install give 404 error

### ISSUE THREAD

**Issue by trasherdk** [linthtml/gulp-linthtml#1]
When running `npm install @linthml/gulp-linthtml`
The response is:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@linthml%2fgulp-linthtml - Not found
npm ERR! 404 
npm ERR! 404  '@linthml/gulp-linthtml@latest' is not in the npm registry.
```
But [@linthtml/gulp-linthtml](https://www.npmjs.com/package/@linthtml/gulp-linthtml) it's there.

**Comment by KamiKillertO** [comment]
It's a typo sorry about that 😅 . You should call `npm install @linthtml/gulp-linthtml`

**Comment by trasherdk** [comment]
Okay, got it.
Thanks.
